# application-dev.yml
server:
  port: 8080

spring:
  application:
    name: Jjin

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

logging:
  level:
    org.hibernate.SQL: info

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 3600000
  refresh-token-expiry: 1209600000

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

encryption:
  secret: ${ENCRYPTION_SECRET}

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URL}
    token-uri: https://oauth2.googleapis.com/token
    userinfo-uri: https://www.googleapis.com/oauth2/v3/userinfo

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when_authorized